# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogGradle@1
  inputs:
    #gradleBuildFile: 'build.gradle'
    tasks: 'artifactoryPublish'
    artifactoryResolverService: 'arti'
    sourceRepo: 'sri-multi-modile-gradle-dev'
    artifactoryDeployerService: 'arti'
    targetRepo: 'sri-multi-modile-gradle-dev'
    usesPlugin: true
    useWrapper: true
    javaHomeOption: 'JDKVersion'
